
- name: Install MongoDB 3.2
  hosts: all
  become: true
  tasks:
  - name: install apt-transport-https
    apt:
      name: apt-transport-https

  - name: install ca-certificates
    apt:
      name: ca-certificates

  - name: update apt
    apt: update_cache=yes force_apt_get=yes cache_valid_time=360

  - name: Add APT key
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-4.2.asc

  - name: Add APT repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
      state: present

  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: present

  - name: Configure service supervisor
    systemd:
      name: mongod
      enabled: yes
